version: 2.1

orbs: 
  node: circleci/node@7.1.0

jobs: 
  lint_code:
    executor: 
      name: node/default
      tag: "22.14.0" 
    description: Lint the code
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Lint the code
          command: npm run lint:fix
          
  run_tests:
    executor: 
      name: node/default
      tag: "22.14.0" 
    description: Run the tests
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run the tests
          command: npm run test
          
  build:
    executor: 
      name: node/default
      tag: "22.14.0" 
    description: Build the code
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build the code
          command: npm run build

  release:
    executor: 
      name: node/default
      tag: "22.14.0" 
    description: Release the code
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Set up git credentials
          command: |
            git config --global user.email $GIT_EMAIL
            git config --global user.name $GIT_NAME
      - run:
          name: Run release
          command: |
            npm run release
            git push --follow-tags "https://${GH_TOKEN}@github.com/imran-codes/react-component-library.git" main
  
  publish:
    executor: 
      name: node/default
      tag: "22.14.0" 
    description: Publish to npm
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Check if npm version is the same and publish to npm
          command: |
            CURRENT_VERSION=$(npm show shadow-ui version)
            LOCAL_VERSION=$(node -pe "require('./package.json').version")

            if [ "$CURRENT_VERSION" != "$LOCAL_VERSION" ]; then
              echo "Versions are different. Publishing to npm."
              echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
              npm publish
            else
              echo "Versions are the same. Skipping npm publish."
            fi

workflows: 
  build_app:
    jobs:
      - lint_code
      - run_tests:
          requires:
            - lint_code
      - build:
          requires:
            - run_tests
            - lint_code
      - release:
          requires:
            - build
            - run_tests
            - lint_code
      - publish:
          requires:
            - release